---
env:
  contexts:
    - name: juice-shop-context
      urls:
        - http://localhost:3000
      includePaths: []
      excludePaths: []
      authentication:
        method: "json"
        parameters:
          loginUrl: "http://localhost:3000/rest/user/login"
          loginRequestData: '{"email":"{%username%}","password":"{%password%"}'
        verification:
          method: "response"
          loggedInRegex: '\bLogout\b'
          loggedOutRegex: '\bUnauthorized\b'
          pollFrequency: 10
      users:
        - name: "admin-user"
          credentials:
            username: "admin@juice-sh.op"
            password: "admin123"
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: replacer
    rules:
      - description: "Inject Admin Token"
        matchType: "req_header"
        matchString: "Authorization"
        replacementString: "Bearer {%token%}"

  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 0
      scanOnlyInScope: true

  - type: openapi
    parameters:
      context: juice-shop-context
      targetUrl: http://localhost:3000
      file: /zap/wrk/swagger.yml

  - type: activeScan
    parameters:
      context: juice-shop-context
      maxScanDurationInMins: 10
      maxRuleDurationInMins: 2

  - type: report
    parameters:
      template: modern
      reportDir: /zap/wrk
      reportFile: juiceshop-automation-output.html