---
env:
  contexts:
    - name: juice-shop-context
      urls:
        - http://localhost:3000
      includePaths: []
      excludePaths: []
      authentication:
        method: "json"
        parameters:
          loginUrl: "http://localhost:3000/rest/user/login"
          loginRequestData: '{"email":"{%username%}","password":"{%password%"}'
        verification:
          method: "response"
          loggedInRegex: '\bLogout\b'
          loggedOutRegex: '\bUnauthorized\b'
          pollFrequency: 10
      users:
        - name: "admin-user"
          credentials:
            username: "admin@juice-sh.op"
            password: "admin123"
  parameters:
    failOnError: true
    progressToStdout: true

jobs:
  - type: replacer
    parameters:
      replacers:
        - description: "Inject Admin Token"
          type: "add_header"
          matchString: "Authorization"
          replacement: "Bearer {%token%}"
          enabled: true

  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 0
      scanOnlyInScope: true

  - type: spiderAjax
    parameters:
      context: juice-shop-context
      url: http://localhost:3000
      browserId: firefox-headless
      runOnlyIfModern: false

  - type: activeScan
    parameters:
      context: juice-shop-context
      maxScanDurationInMins: 10
      maxRuleDurationInMins: 2

  - type: report
    parameters:
      template: modern
      reportDir: /zap/wrk
      reportFile: juiceshop-automation-output